name: Deploy

on:
  pull_request:

jobs:
  Site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID}}
          VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID_SITE}}
